### PR TITLE
Removed "function/code stack" debugging configure option

### PR DESCRIPTION
**Pull request by qkoziol**
Easily replaced w/third-party tools, e.g. libbacktrace (https://github.com/ianlancetaylor/libbacktrace)

### CODE REVIEW

**Comment by derobins** [comment]
This should probably not be merged to 1.14, even though it's removing an obscure, broken feature. We can discuss in the working group, though.

**Comment by qkoziol** [comment]
> This should probably not be merged to 1.14, even though it's removing an obscure, broken feature. We can discuss in the working group, though.

Agree - no sense disrupting the branch, even if it's not working.

**Comment by qkoziol** [comment]
The "free list tracking" code was also removed, since it was the reason that the function stack was added originally.  (And using libbacktrace can avoid all this framework)

**Review by derobins — APPROVED** [review]

**Comment by derobins** [comment]
We decided this feature could be removed from 1.14 since it's currently broken (and didn't even compile until recently). Anyone who cared would have complained by now.

**Review by jhendersonHDF — APPROVED** [review]

**Pull request merged**
