### PR TITLE
Revert "Addressed Fortran  issues with promoted integers and reals via compilation flags"

### PR DESCRIPTION
**Pull request by brtnfld**
Reverts HDFGroup/hdf5#4209

### CODE REVIEW

**Comment by brtnfld** [comment]
I need to add the changes I made to logical kinds.

**Review by lrknox — APPROVED** [review]

**Comment by jhendersonHDF** [comment]
Is it more difficult than just adding those changes in?

**Comment by brtnfld** [comment]
I would have to merge the changes to the branch that I made after the merge, the changes touch a lot. I can see how it goes.

**Comment by jhendersonHDF** [comment]
> I would have to merge the changes to the branch that I made after the merge, the changes touch a lot. I can see how it goes.

Fair enough, probably easiest to go this way then.

**Review by jhendersonHDF — APPROVED** [review]

**Comment by brtnfld** [comment]
Yeah, I would have to fix the conflicts.

**Review by derobins — APPROVED** [review]

**Pull request merged**
