### PR TITLE
Add Julia GitHub Actions.

### LINKED ISSUE #3857: Add CI testing for HDF5/Julia
We should add HDF5 Julia https://github.com/JuliaIO/HDF5.jl testing to either a CI action or as a daily test.

### PR DESCRIPTION
**Pull request by hyoklee**
These minimal Actions test the latest release version (1.6) of HDF5 Julia with HDF5 develop branch.

Both CMake and Autotools Actions fail as of 2024-03-12:

```
Test Summary:                      | Pass  Fail  Broken  Total
HDF5.jl                            | 1498     1       3   1502
  plain                            |  151             1    152
```

Action names follow this [convention](https://github.com/hyoklee/hdf5/wiki/Actions).

close #3857

### CODE REVIEW

**Comment by derobins** [comment]
Why does this pass if the interface has breakage?

**Comment by mkitti** [comment]
```
properties: Test Failed at /home/runner/work/hdf5/hdf5/test/properties.jl:73
  Expression: fapl.libver_bounds == (:earliest, Base.thisminor(HDF5.libversion))
   Evaluated: (:earliest, v"1.14.0") == (:earliest, v"1.15.0")
```

**Comment by hyoklee** [comment]
Hi, @mkitti ! 

Thank you so much for checking failure and asking developers to check this CI.

Is there a quick way to disable the version test using `julia-actions/julia-runtest@latest`? 

Also, how can I examine `broken` tests?

Regards,

**Comment by derobins** [comment]
If this is a version problem, can it be merged to the 1.14 branch?

**Comment by mkitti** [comment]
I plan on changing the test. I'll do this today.

**Comment by mkitti** [comment]
Here we are testing if the default FAPL libver_bounds is earliest to latest.

The issue is we need to infer the value of `H5F_LIBVER_LATEST` and this test should use that value.

**Comment by mkitti** [comment]
> Also, how can I examine `broken` tests?

The broken tests are tests that are known to not work. If the tests actually do work, then the test system will report a failure suggesting that we should no longer mark the tests as broken.

**Comment by mkitti** [comment]
This should work now after https://github.com/JuliaIO/HDF5.jl/pull/1145. Please re-run the tests.

**Comment by jhendersonHDF** [comment]
> This should work now after [JuliaIO/HDF5.jl#1145](https://github.com/JuliaIO/HDF5.jl/pull/1145). Please re-run the tests.

Seems like the Julia actions passed. Thanks @mkitti!

**Comment by mkitti** [comment]
By the way, the latest stable release is Julia 1.10.2:
https://julialang.org/downloads/

Julia 1.6 is the latest Long Term Support (LTS) release.

**Review by byrnHDF — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

**Pull request merged**
