### PR TITLE
Fixes #1946

### LINKED ISSUE #1946: External link styling broken
`hdf5doxy.css` references the defunct `https://mdn.mozillademos.org/files/12982/external-link-52.png`

### PR DESCRIPTION
**Pull request by gheber**

### CODE REVIEW

**Review by byrnHDF — COMMENTED** [review]
I have a different fix this.

**Comment by gheber** [comment]
Where is your fix?

**Review by derobins — APPROVED** [review]

**Comment by byrnHDF** [comment]
a[href*="https://"] {
  background: url('./Icon_External_Link.png') no-repeat 100% 0;
  background-size: 12px 12px;
  padding-right: 16px;
}

We can use a local copy saved in img folder.

**Comment by derobins** [comment]
> a[href*="https://"] {
> 
> # background: url('https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Icon_External_Link.svg/120px-Icon_External_Link.svg.png') no-repeat 100% 0;
> background: url('./Icon_External_Link.png') no-repeat 100% 0; background-size: 12px 12px; padding-right: 16px; }
> 
> We can use a local copy saved in img folder.

I feel like a local copy is better than something off the internet.

**Comment by gheber** [comment]
My solution doesn't require anything. It renders SVG in place.

**Comment by derobins** [comment]
> My solution doesn't require anything. It renders SVG in place.

Ah, I see that now. Very nice!

**Comment by byrnHDF** [comment]
It still requires an internet connection and I know there have been issues in the past with some customers. The file is a whopping 144 bytes!

**Comment by gheber** [comment]
Mine doesn't. It renders locally.

**Comment by byrnHDF** [comment]
So all those numbers in the URL are datapoints to draw?

**Comment by byrnHDF** [comment]
If so - okay then.

**Comment by gheber** [comment]
Yup. It's like PostScript in the old days...

**Comment by gheber** [comment]
[Styling External Links with an Icon in CSS](https://christianoliff.com/blog/styling-external-links-with-an-icon-in-css/)

**Pull request merged**
