### PR TITLE
Fix LOG VOL CI not including Zlib

### PR DESCRIPTION
**Pull request by mattjala**
#5085 changed the default for zlip support to 'off', so the CI should now specifically turn this one. The LOG VOL CI is currently failing two compression tests due to this issue.

### CODE REVIEW

**Review by byrnHDF — APPROVED** [review]

**Review by jhendersonHDF — CHANGES_REQUESTED** [review]
Since the workflow was already explicitly turning off zlib support before, we need to determine why the default being changed to OFF is now causing the LOG VOL CI to fail and fix that issue, rather than enabling zlib support to paper over the issue.

**Comment by mattjala** [comment]
> Since the workflow was already explicitly turning off zlib support before, we need to determine why the default being changed to OFF is now causing the LOG VOL CI to fail and fix that issue, rather than enabling zlib support to paper over the issue.

The  workflow wasn't explicitly turning off zlib before. It used to include zlib by default like everything else. In the PR that changed the zlib default to off, the "ZLIB=OFF" line was redundantly added to the workflow. That should have been ZLIB=ON.

**Review by hyoklee — APPROVED** [review]

**Comment by jhendersonHDF** [comment]
> > Since the workflow was already explicitly turning off zlib support before, we need to determine why the default being changed to OFF is now causing the LOG VOL CI to fail and fix that issue, rather than enabling zlib support to paper over the issue.
> 
> The workflow wasn't explicitly turning off zlib before. It used to include zlib by default like everything else. In the PR that changed the zlib default to off, the "ZLIB=OFF" line was redundantly added to the workflow. That should have been ZLIB=ON.

I don't believe the line was redundant; more that it was either a copy-paste or wasn't functioning as intended before. Either way, this still seems to point to an issue that needs to be fixed on the LOG VOL's side before re-enabling ZLIB. Otherwise, the issue will go unfixed. @brtnfld do you happen to know anything about this?

**Comment by brtnfld** [comment]
I'm unaware of how zlib is being tested in the log-vol; I've created an issue https://github.com/HDFGroup/vol-log-based/issues/75 to determine what's happening.

**Review by jhendersonHDF — APPROVED** [review]

**Pull request merged**
