### PR TITLE
Remove unused #cmakedefine checks

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by derobins** [comment]
I'll pull these in the autotools, too. You can add my repo as a remote and we'll get them both in together. Are you going to modify the CMake code that checks and sets these variables?

**Comment by seanm** [comment]
>Are you going to modify the CMake code that checks and sets these variables?

Where would that be?  Like I said, searching for, for example, `H5_HAVE_LLROUND` finds nothing nowhere.

**Comment by seanm** [comment]
Ah, nevermind, searching for `HAVE_LLROUND` without the `H5` prefix finds stuff...

**Comment by derobins** [comment]
Right. The H5_ prefix gets prepended, as we do in the Autotools.

**Comment by seanm** [comment]
Doh. Hadn't thought of that prefix thing... so some things aren't as dead as I thought.  I restored some.

**Comment by derobins** [comment]
No worries. It's good to go over the configure options every once in a while and every time we do it's a journey of discovery.

**Comment by seanm** [comment]
@derobins any additional changes needed here?

**Review by byrnHDF — APPROVED** [review]

**Comment by lrknox** [comment]
> 
> 
> @derobins any additional changes needed here?

@seanm removing line 2057: "AC_CHECK_FUNCS([roundf lroundf llroundf round lround llround])" should remove the Autotools equivalent checks, if you want to add that to this pull request.

**Comment by seanm** [comment]
@lrknox thx & done.

**Review by lrknox — APPROVED** [review]

**Pull request merged**
