### PR TITLE
Fix for a tools compile issue when deprecated symbols are disabled

### PR DESCRIPTION
**Pull request by derobins**
Introduced in #1811, also uses VOL token instead of addr

### CODE REVIEW

**Comment by byrnHDF** [comment]
> Introduced in #1811, also uses VOL token instead of addr

Does this also apply to 1.12 or was it after 1.12 these were added?

**Review by byrnHDF — APPROVED** [review]

**Comment by derobins** [comment]
> > Introduced in #1811, also uses VOL token instead of addr
> 
> Does this also apply to 1.12 or was it after 1.12 these were added?

I'll check and merge if appropriate. Pretty sure it goes to 1.12.

**Review by jhendersonHDF — APPROVED** [review]

**Review by lrknox — CHANGES_REQUESTED** [review]
There are similar errors for versioned H5O_info_1_t, etc in java/src/jni/h5util.c.  I'll take a look - probably the fix is similar there.

**Comment by derobins** [comment]
> There are similar errors for versioned H5O_info_1_t, etc in java/src/jni/h5util.c. I'll take a look - probably the fix is similar there.

I just built the fix branch w/ Java and --disable-deprecated-symbols and don't see problems. Everything in java/src/jni/h5util.c uses H5O_info2_t (in develop, at least). I'll keep an eye out for problems in 1.12.

**Comment by derobins** [comment]
I don't see other failures, so I'm going to merge this now so it at least fixes one problem. I'll fix any others that crop up in separate PRs.

**Pull request merged**
