### PR TITLE
Fixed -Wcomment warning about /* within /*

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@qkoziol an easy one...

**Comment by byrnHDF** [comment]
This is being taken care of in a current issue, which should have a PR any day now.

**Review by derobins — APPROVED** [review]

**Comment by derobins** [comment]
Actually, we don't allow C++ EOL comments in C code.

**Review by derobins — CHANGES_REQUESTED** [review]
Should be a C-style comment

**Comment by seanm** [comment]
It ***is*** a C style comment.  `//` has been a valid C comment marker for 22 years now.

**Comment by byrnHDF** [comment]
Really, this PR is unnecessary - new code will appear real soon - working on the issue that this code involves today.

**Comment by derobins** [comment]
> It _**is**_ a C style comment. `//` has been a valid C comment marker for 22 years now.

Tell me about it. That's the current library style, though.

**Comment by seanm** [comment]
>Tell me about it. That's the current library style, though.

:) But the codebase already requires C99 and all major C compilers have supported // forever, so what purpose does such a style requirement serve? Perhaps time to revisit it?

**Comment by qkoziol** [comment]
I think we can relax toward allowing the "//" string for comments - the recent Doxygen commits have used the '//' string for many of its comments.

**Comment by byrnHDF** [comment]
I have a PR that will take care of this - this morning after I clean it up to commit.

**Pull request closed without merging**
