### PR TITLE
Remove racey start condition for ping thread

### PR DESCRIPTION
**Pull request by qkoziol**

### CODE REVIEW

**Comment by qkoziol** [comment]
@lrknox - I believe that this should address the intermittent failure for the semaphore test

**Review by lrknox — APPROVED** [review]
So far this seems to fix the tests that intermittently fail.

**Review by byrnHDF — APPROVED** [review]

**Comment by lrknox** [comment]
@qkoziol this may have addressed the intermittent failure on the machines where it was first noticed, but there are still some on machines with newer compilers (gcc 10 & 12, clang 18 on ubuntu 24.04, oneapi 2023). It's too soon to say whether those are intermittent or fail consistently.

**Comment by qkoziol** [comment]
> @qkoziol this may have addressed the intermittent failure on the machines where it was first noticed, but there are still some on machines with newer compilers (gcc 10 & 12, clang 18 on ubuntu 24.04, oneapi 2023). It's too soon to say whether those are intermittent or fail consistently.

OK, thanks for the update.   Are those configurations in the CI action, so I could test against them?

**Comment by lrknox** [comment]
@qkoziol Autotools TestExpress Workflows / Autotools debug Express Test Workflows failed the  ttsafe test in the action after I merged #4694.  Can you try that one?

These links show the ttsafe test failures reported to the 2 CDash instances for 8/6:
https://my.cdash.org/testSummary.php?project=1850&name=H5TEST-ttsafe&date=2024-08-06
https://cdash.hdfgroup.org/testSummary.php?project=7&name=H5TEST-ttsafe&date=2024-08-06

Clang is the compiler most common in these failures, followed by Intel (oneAPI) and gcc 11,12,13.  
The most common machine for the failures last week was ec2-centos8, with either gcc 8.5, IntelLLVM 2024.1.0, or clang 12.0.1:  https://my.cdash.org/testSummary.php?project=1850&name=H5TEST-ttsafe&date=2024-08-02

You can find the compiler and configure command for the failed tests in the links above by clicking on "Failed", then on the build name link, and then on the "0" for configure errors.

**Comment by qkoziol** [comment]
@lrknox - I spent a while poking at this before I noticed that I was accessing a variable outside of the semaphore protection.  This PR:  https://github.com/HDFGroup/hdf5/pull/4725 should fix the problem.

**Pull request merged**
