### PR TITLE
Add MINGW64 Cross-compilation Action

### PR DESCRIPTION
**Pull request by hyoklee**
This PR is for #3973.

221 tests fail as of 2024-03-18.

See also: https://my.cdash.org/viewTest.php?onlyfailed&buildid=2522141

### CODE REVIEW

**Comment by mkitti** [comment]
You may be interested in how MSYS2 builds HDF5:
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-hdf5

**Comment by mkitti** [comment]
In particular this patch:
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-hdf5/hdf5-proper-library-names-mingw.patch

**Review by bmribler — APPROVED** [review]

**Review by byrnHDF — CHANGES_REQUESTED** [review]
This needs to be standardized with the rest of the workflows

**Comment by fortnern** [comment]
Closed at Joe's request

**Comment by mkitti** [comment]
Who is Joe?

**Comment by lrknox** [comment]
> Who is Joe?

Joe Lee, the original author.

**Pull request closed without merging**
