### PR TITLE
Update GitHub macOS actions to v13

### LINKED ISSUE #1289: test/accum.c  CTest fails on macOS Monterey
```
19: Testing SWMR write of large metadata: with latest format              *FAILED*
19:    at /Users/hyoklee/src/hdf5/test/accum.c:2291 in test_swmr_write_big()...
19: child process exited abnormally
19: Testing SWMR write of large metadata: with non-latest-format          *FAILED*
19:    at /Users/hyoklee/src/hdf5/test/accum.c:2291 in test_swmr_write_big()...
19: child process exited abnormally
19: *** TESTS FAILED ***
```

### LINKED ISSUE #2261: accum test fails on macOS 12
19: Testing simple freeing metadata accumulator                            PASSED
19: Testing large metadata I/O operations                                  PASSED
19: Testing random writes to accumulator                                   PASSED
19: Testing SWMR write of large metadata: with latest format              *FAILED*
19:    at /Users/runner/work/hdf5/hdf5/test/accum.c:2292 in test_swmr_write_big()...
19: child process exited abnormally
19: Testing SWMR write of large metadata: with non-latest-format          *FAILED*
19:    at /Users/runner/work/hdf5/hdf5/test/accum.c:2292 in test_swmr_write_big()...
19: child process exited abnormally
19: *** TESTS FAILED ***
19: 
The relevant code in accum.c (function test_swmr_write_big) that triggers the error:
    {
        pid_t pid;    /* Process ID */
        int   status; /* Status returned from child process */

        /* Fork child process to verify that the data at [1024, 2014] does get written to disk */
        if ((pid = HDfork()) < 0) {
            HDperror("fork");
            FAIL_STACK_ERROR;
        }
        else if (0 == pid) { /* Child process */
            /* By convention, argv[0] tells the name of program invoked.
             *
             * execv on NetBSD 8 will actually return EFAULT if there is a
             * NULL at argv[0], so we follow the convention unconditionally.
             */
            char        swmr_reader[] = SWMR_READER;
            char *const new_argv[]    = {swmr_reader, NULL};
            /* Run the reader */
            status = HDexecv(SWMR_READER, new_argv);
            HDprintf("errno from execv = %s\n", HDstrerror(errno));
            FAIL_STACK_ERROR;
        } /* end if */

        /* Parent process -- wait for the child process to complete */
        while (pid != HDwaitpid(pid, &status, 0))
            /*void*/;

        /* Check if child process terminates normally and its return value */
        if (WIFEXITED(status) && !WEXITSTATUS(status))
            process_success = TRUE;
    }

### LINKED ISSUE #2994: [Feature Request] Add macOS-13 action.
https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/

### PR DESCRIPTION
**Pull request by derobins**
Fixes #2994
Fixes #1289
Fixes #2261

### CODE REVIEW

**Review by brtnfld — APPROVED** [review]
LGTM

**Comment by lrknox** [comment]
Specific test failure:
19: Testing SWMR write of large metadata: with latest format              *FAILED*
19:    at /Users/runner/work/hdf5/hdf5/test/accum.c:2291 in test_swmr_write_big()...
19: child process exited abnormally
19: Testing SWMR write of large metadata: with non-latest-format          *FAILED*
19:    at /Users/runner/work/hdf5/hdf5/test/accum.c:2291 in test_swmr_write_big()...
19: child process exited abnormally
19: *** TESTS FAILED ***

**Comment by derobins** [comment]
> Specific test failure: 19: Testing SWMR write of large metadata: with latest format _FAILED_ 19: at /Users/runner/work/hdf5/hdf5/test/accum.c:2291 in test_swmr_write_big()... 19: child process exited abnormally 19: Testing SWMR write of large metadata: with non-latest-format _FAILED_ 19: at /Users/runner/work/hdf5/hdf5/test/accum.c:2291 in test_swmr_write_big()... 19: child process exited abnormally 19: *** TESTS FAILED ***

I'm looking into it. The test is fine when run directly and only fails when run via CTest. Autotools is also fine. It's weird that there's a change when going from macOS 11 to 13.

**Review by byrnHDF — APPROVED** [review]

**Comment by derobins** [comment]
There are other places where LD_LIBRARY_PATH is used that probably need updating, but that's getting out of scope for this PR...

**Pull request merged**
