### PR TITLE
Fix bugs in parallel selection I/O

### PR DESCRIPTION
**Pull request by fortnern**

### CODE REVIEW

**Comment by fortnern** [comment]
This will be tested by the multi dataset tests

**Review by epourmal — APPROVED** [review]
Looks very good to me. Question: why we cannot use `size_t` for `count`?

**Review by jhendersonHDF — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]

**Comment by fortnern** [comment]
> Looks very good to me. Question: why we cannot use `size_t` for `count`?

I think it's because MPI_Type_create_struct(), etc. take an int for the count. I'm not sure why it's uin32_t instead of int though.

**Comment by epourmal** [comment]
> > Looks very good to me. Question: why we cannot use `size_t` for `count`?
> 
> I think it's because MPI_Type_create_struct(), etc. take an int for the count. I'm not sure why it's uin32_t instead of int though.

If it comes from `MPI_Type_create_struct()`, we should use `int`. My guess about `uin32_t `is that someone wanted to enforce unsigned 32-bit value, but if MPI needs `int,` we should use `int`. There is not guarantee, that `int `is a 32-bit number, right? If we need to check the range to avoid MPI bugs or something like this, it should be done explicitly and not by using C datatype. But this is my "non-programmer" opinion :-)

**Pull request merged**
