### PR TITLE
Clang warnings and ASan fixes

### PR DESCRIPTION
**Pull request by seanm**
This fixes a few compiler warnings and ASan reports.

### CODE REVIEW

**Comment by epourmal** [comment]
Sean,

Thank you so much for your contribution! This repo is not open for contributions yet. We will be announcing our move from Bitbucket to Github before the end of July. 

Could you please submit your patch against https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse and we will review and merge, or could you please wait until we make an announcement? 

Our repo doesn't have standard git organization and all changes should be done to develop branch first and then we will propagate the changes to the other maintenance branches.

Thank you!

Elena

**Comment by seanm** [comment]
The only one I really need ASAP is 29e6401, because it prevents compilation on the beta of macOS 11 Big Sur because the -Wimplicit-function-declaration warning is now treated as an error.

Building the 'develop' branch doesn't seem to have those warnings.  I guess someone fixed them already.  Given that, there's no change to the 'develop' branch I can even submit.  How to proceed?  Thanks.

**Comment by lrknox** [comment]
Hi Sean,

I checked for the 29e6401 changes in our 1.10 development branch hdf5_1_10, and they are in that branch.  I suspect that if the rest of these changes are in develop, they are also in the hdf5_1_10 branch.  we currently reserve the 1.x/master branches for committing official releases.  The code currently in hdf5_1_10 with another month's work should be posted there sometime in August.  If the changes you need are in that branch, can you use the branch?  I can also create a snapshot release from that branch this weekend, and if the branch doesn't have all of your changes we can review them and try to get them into the snapshot.

Larry

**Comment by seanm** [comment]
>This repo is not open for contributions yet.

Is it now?

I've just updated myself to c55ac8ab7126f101bf704a54824c0a55f410e105 on develop branch and 3 tests fail with address sanitizer, specifically:

```
	 26 - H5TEST-dsets (Failed)
	2082 - HL_test_table (Failed)
	2107 - CPP_testhdf5 (Failed)
```

Probably the same 3 as in my patch...

**Comment by byrnHDF** [comment]
I have implemented some of these changes (not the CX includes yet) that are applicable.
It has fixed two tests; CPP_testhdf5 and HL_test_table.

**Comment by seanm** [comment]
Great, thanks.  But where?  I don't see it here: https://github.com/HDFGroup/hdf5/commits/develop  am I looking in the wrong place?

**Comment by byrnHDF** [comment]
Still on my local machine - need to create PRs. 
Need to look into the rest.

**Comment by seanm** [comment]
Ah, I see.  Can this PR not be used?

**Comment by byrnHDF** [comment]
> Ah, I see. Can this PR not be used?

Right, this PR is against 1.10/master which is "release tagging" branch. The normal process is develop, to 1.12, to 1.10, to 1.8.
I will have 4 PRs up soon after testing is verified.

**Comment by byrnHDF** [comment]
PR #312 , #313 , #314 and #315 created for these changes.

**Comment by seanm** [comment]
Great thanks!

**Comment by seanm** [comment]
So I can confirm that two are fixed, and `H5TEST-dsets` is not.  I debugged it a bit:

`H5MM_memcpy` is reading past the end of a 32 byte buffer because it's being told to read 256 bytes.  The buffer is:

https://github.com/HDFGroup/hdf5/blob/52ac74689a869b4ae40801e6096a1f037aad0081/test/dsets.c#L12185

The backtrace is:

```
frame #5: 0x0000000101490c5c libhdf5_debug.1000.dylib`H5MM_memcpy(dest=0x00006120004816c8, src=0x00000001000f7120, n=256) at H5MM.c:606:11
frame #6: 0x00000001026ddbd1 libhdf5_debug.1000.dylib`H5VM_memcpyvv(_dst=0x00006120004816c8, dst_max_nseq=1, dst_curr_seq=0x00007ffeefbfbae0, dst_len_arr=0x0000625000005108, dst_off_arr=0x0000625000007908, _src=0x00000001000f7120, src_max_nseq=1, src_curr_seq=0x00007ffeefbfbac0, src_len_arr=0x0000625000000108, src_off_arr=0x0000625000002908) at H5VM.c:1625:13
frame #7: 0x00000001009c0b83 libhdf5_debug.1000.dylib`H5D__compact_writevv(io_info=0x00007ffeefbfc570, dset_max_nseq=1, dset_curr_seq=0x00007ffeefbfbae0, dset_size_arr=0x0000625000005108, dset_offset_arr=0x0000625000007908, mem_max_nseq=1, mem_curr_seq=0x00007ffeefbfbac0, mem_size_arr=0x0000625000000108, mem_offset_arr=0x0000625000002908) at H5Dcompact.c:314:22
frame #8: 0x0000000100b1634a libhdf5_debug.1000.dylib`H5D__select_io(io_info=0x00007ffeefbfc570, elmt_size=4, nelmts=64, file_space=0x0000613000b5fe80, mem_space=0x000061300053afc0) at H5Dselect.c:221:37
frame #9: 0x0000000100b172b3 libhdf5_debug.1000.dylib`H5D__select_write(io_info=0x00007ffeefbfc570, type_info=0x00007ffeefbfd110, nelmts=64, file_space=0x0000613000b5fe80, mem_space=0x000061300053afc0) at H5Dselect.c:310:9
frame #10: 0x00000001008fdb49 libhdf5_debug.1000.dylib`H5D__chunk_write(io_info=0x00007ffeefbfd020, type_info=0x00007ffeefbfd110, nelmts=64, file_space=0x000061300053afc0, mem_space=0x000061300053afc0, fm=0x0000620000000080) at H5Dchunk.c:2730:13
frame #11: 0x0000000100ae05be libhdf5_debug.1000.dylib`H5D__write(dataset=0x0000606000013580, mem_type_id=216172782113784762, mem_space=0x000061300053afc0, file_space=0x000061300053afc0, buf=0x00000001000f7120) at H5Dio.c:531:9
frame #12: 0x000000010265d946 libhdf5_debug.1000.dylib`H5VL__native_dataset_write(obj=0x0000606000013580, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, req=0x0000000000000000) at H5VLnative_dataset.c:206:9
frame #13: 0x00000001025aebea libhdf5_debug.1000.dylib`H5VL__dataset_write(obj=0x0000606000013580, cls=0x0000616000000980, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, req=0x0000000000000000) at H5VLcallback.c:2082:9
frame #14: 0x00000001025ae050 libhdf5_debug.1000.dylib`H5VL_dataset_write(vol_obj=0x0000603000006640, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, req=0x0000000000000000) at H5VLcallback.c:2114:9
frame #15: 0x000000010088d551 libhdf5_debug.1000.dylib`H5D__write_api_common(dset_id=360287970189640115, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, token_ptr=0x0000000000000000, _vol_obj_ptr=0x0000000000000000) at H5D.c:1105:9
frame #16: 0x000000010088c561 libhdf5_debug.1000.dylib`H5Dwrite(dset_id=360287970189640115, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=0, buf=0x00000001000f7120) at H5D.c:1154:9
frame #17: 0x00000001000b856b dsets`test_bt2_hdr_fd(env_h5_driver="nomatch", fapl=792633534417208475) at dsets.c:12488:9
frame #18: 0x0000000100007390 dsets`main at dsets.c:15270:29
```

```
(lldb) fr sel 6
frame #6: 0x00000001026ddbd1 libhdf5_debug.1000.dylib`H5VM_memcpyvv(_dst=0x00006120004816c8, dst_max_nseq=1, dst_curr_seq=0x00007ffeefbfbae0, dst_len_arr=0x0000625000005108, dst_off_arr=0x0000625000007908, _src=0x00000001000f7120, src_max_nseq=1, src_curr_seq=0x00007ffeefbfbac0, src_len_arr=0x0000625000000108, src_off_arr=0x0000625000002908) at H5VM.c:1625:13
   1622	        acc_len = 0;
   1623	        do {
   1624	            /* Copy data */
-> 1625	            H5MM_memcpy(dst, src, tmp_dst_len);
   1626	
   1627	            /* Accumulate number of bytes copied */
   1628	            acc_len += tmp_dst_len;

(lldb) p tmp_dst_len
(size_t) $11 = 256

(lldb) p tmp_src_len
(size_t) $12 = 256
```

I gave up at that point, but hopefully it gives you a head start.

**Comment by seanm** [comment]
So I can confirm that two are fixed, and `H5TEST-dsets` is not.  I debugged it a bit:

`H5MM_memcpy` is reading past the end of a 32 byte buffer because it's being told to read 256 bytes.  The buffer is:

https://github.com/HDFGroup/hdf5/blob/52ac74689a869b4ae40801e6096a1f037aad0081/test/dsets.c#L12185

`const int         buffer[8]   = {0, 1, 2, 3, 4, 5, 6, 7};`

The backtrace is:

```
frame #5: 0x0000000101490c5c libhdf5_debug.1000.dylib`H5MM_memcpy(dest=0x00006120004816c8, src=0x00000001000f7120, n=256) at H5MM.c:606:11
frame #6: 0x00000001026ddbd1 libhdf5_debug.1000.dylib`H5VM_memcpyvv(_dst=0x00006120004816c8, dst_max_nseq=1, dst_curr_seq=0x00007ffeefbfbae0, dst_len_arr=0x0000625000005108, dst_off_arr=0x0000625000007908, _src=0x00000001000f7120, src_max_nseq=1, src_curr_seq=0x00007ffeefbfbac0, src_len_arr=0x0000625000000108, src_off_arr=0x0000625000002908) at H5VM.c:1625:13
frame #7: 0x00000001009c0b83 libhdf5_debug.1000.dylib`H5D__compact_writevv(io_info=0x00007ffeefbfc570, dset_max_nseq=1, dset_curr_seq=0x00007ffeefbfbae0, dset_size_arr=0x0000625000005108, dset_offset_arr=0x0000625000007908, mem_max_nseq=1, mem_curr_seq=0x00007ffeefbfbac0, mem_size_arr=0x0000625000000108, mem_offset_arr=0x0000625000002908) at H5Dcompact.c:314:22
frame #8: 0x0000000100b1634a libhdf5_debug.1000.dylib`H5D__select_io(io_info=0x00007ffeefbfc570, elmt_size=4, nelmts=64, file_space=0x0000613000b5fe80, mem_space=0x000061300053afc0) at H5Dselect.c:221:37
frame #9: 0x0000000100b172b3 libhdf5_debug.1000.dylib`H5D__select_write(io_info=0x00007ffeefbfc570, type_info=0x00007ffeefbfd110, nelmts=64, file_space=0x0000613000b5fe80, mem_space=0x000061300053afc0) at H5Dselect.c:310:9
frame #10: 0x00000001008fdb49 libhdf5_debug.1000.dylib`H5D__chunk_write(io_info=0x00007ffeefbfd020, type_info=0x00007ffeefbfd110, nelmts=64, file_space=0x000061300053afc0, mem_space=0x000061300053afc0, fm=0x0000620000000080) at H5Dchunk.c:2730:13
frame #11: 0x0000000100ae05be libhdf5_debug.1000.dylib`H5D__write(dataset=0x0000606000013580, mem_type_id=216172782113784762, mem_space=0x000061300053afc0, file_space=0x000061300053afc0, buf=0x00000001000f7120) at H5Dio.c:531:9
frame #12: 0x000000010265d946 libhdf5_debug.1000.dylib`H5VL__native_dataset_write(obj=0x0000606000013580, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, req=0x0000000000000000) at H5VLnative_dataset.c:206:9
frame #13: 0x00000001025aebea libhdf5_debug.1000.dylib`H5VL__dataset_write(obj=0x0000606000013580, cls=0x0000616000000980, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, req=0x0000000000000000) at H5VLcallback.c:2082:9
frame #14: 0x00000001025ae050 libhdf5_debug.1000.dylib`H5VL_dataset_write(vol_obj=0x0000603000006640, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, req=0x0000000000000000) at H5VLcallback.c:2114:9
frame #15: 0x000000010088d551 libhdf5_debug.1000.dylib`H5D__write_api_common(dset_id=360287970189640115, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=792633534417207304, buf=0x00000001000f7120, token_ptr=0x0000000000000000, _vol_obj_ptr=0x0000000000000000) at H5D.c:1105:9
frame #16: 0x000000010088c561 libhdf5_debug.1000.dylib`H5Dwrite(dset_id=360287970189640115, mem_type_id=216172782113784762, mem_space_id=0, file_space_id=0, dxpl_id=0, buf=0x00000001000f7120) at H5D.c:1154:9
frame #17: 0x00000001000b856b dsets`test_bt2_hdr_fd(env_h5_driver="nomatch", fapl=792633534417208475) at dsets.c:12488:9
frame #18: 0x0000000100007390 dsets`main at dsets.c:15270:29
```

```
(lldb) fr sel 6
frame #6: 0x00000001026ddbd1 libhdf5_debug.1000.dylib`H5VM_memcpyvv(_dst=0x00006120004816c8, dst_max_nseq=1, dst_curr_seq=0x00007ffeefbfbae0, dst_len_arr=0x0000625000005108, dst_off_arr=0x0000625000007908, _src=0x00000001000f7120, src_max_nseq=1, src_curr_seq=0x00007ffeefbfbac0, src_len_arr=0x0000625000000108, src_off_arr=0x0000625000002908) at H5VM.c:1625:13
   1622	        acc_len = 0;
   1623	        do {
   1624	            /* Copy data */
-> 1625	            H5MM_memcpy(dst, src, tmp_dst_len);
   1626	
   1627	            /* Accumulate number of bytes copied */
   1628	            acc_len += tmp_dst_len;

(lldb) p tmp_dst_len
(size_t) $11 = 256

(lldb) p tmp_src_len
(size_t) $12 = 256
```

I gave up at that point, but hopefully it gives you a head start.

**Comment by seanm** [comment]
I've just confirmed that my warning fixes in this PR are no longer needed vs current `develop` branch.

So just the `H5TEST-dsets` remains...

**Comment by byrnHDF** [comment]
Created #444 issue for dsets test failure

**Pull request closed without merging**
