### PR TITLE
Determine if native connector is terminal

### PR DESCRIPTION
**Pull request by qkoziol**
Use H5VLobject_is_native to determine if the native connector is the terminal connector.

### CODE REVIEW

**Review by derobins — APPROVED** [review]

**Review by byrnHDF — CHANGES_REQUESTED** [review]
Of course that changes a public API, but we don't publish the tools API, so it should be in a release note.

**Comment by derobins** [comment]
I don't consider the tools API a public API. It's like the test API.

**Comment by qkoziol** [comment]
That's confusing - if it's unpublished, why is a release note required?

**Review by byrnHDF — APPROVED** [review]
Would prefer a release note.

**Pull request merged**
