### PR TITLE
First cut of the H5 public API documentation.

### PR DESCRIPTION
**Pull request by gheber**
Nothing earth-shattering here. I had to create `H5module.h` for completeness and sanity.

### CODE REVIEW

**Comment by qkoziol** [comment]
Why create the H5module.h header?

**Comment by gheber** [comment]
> Why create the H5module.h header?

Doxygen has the concept of modules, which, I think, is a good fit for HDF5 modules. There is API documentation (functions, structures, etc.), but perhaps also _module-level documentation_. It's also a convenient placeholder for grouping certain APIs within a given module, which is to a degree arbitrary. See for example `H5Fmodule.h`, where we separated MDC, SWMR, and parallel calls. Alternatively, we could have chosen Beginner, Intermediate, and Advanced, or something else. I think of it as a useful (documentation-)structuring aid, and it makes sense to have a place that's _consistent_ across HDF5 modules for that. Also, what if a module's public API involves multiple header files? The `H5` module came relatively late in the game after we had done most of the others and it just struck me as odd that it didn't have a `*module.h` file.

I think `H5Z` is a good example of module-level documentation. If you look at the stuff on [this page](https://portal.hdfgroup.org/display/HDF5/Filters) that might be clearer.  I'll add it to this PR for reference. You can see it online [here](https://hdf5.io/develop/group___h5_z.html).

**Comment by qkoziol** [comment]
> > Why create the H5module.h header?
> 
> Doxygen has the concept of modules, which, I think, is a good fit for HDF5 modules. There is API documentation (functions, structures, etc.), but perhaps also _module-level documentation_. It's also a convenient placeholder for grouping certain APIs within a given module, which is to a degree arbitrary. See for example `H5Fmodule.h`, where we separated MDC, SWMR, and parallel calls. Alternatively, we could have chosen Beginner, Intermediate, and Advanced, or something else. I think of it as a useful (documentation-)structuring aid, and it makes sense to have a place that's _consistent_ across HDF5 modules for that. Also, what if a module's public API involves multiple header files? The `H5` module came relatively late in the game after we had done most of the others and it just struck me as odd that it didn't have a `*module.h` file.
> 
> I think `H5Z` is a good example of module-level documentation. If you look at the stuff on [this page](https://portal.hdfgroup.org/display/HDF5/Filters) that might be clearer. I'll add it to this PR for reference. You can see it online [here](https://hdf5.io/develop/group___h5_z.html).

I *do* like the idea, but the "module" files have a particular use in the code right now.  For example, I'm not 100% certain that the macro definitions you have in the H5module.h file would be compatible with the H5 "module" code.  (Those macros are used to configure various behavior for the module).    I don't really want to introduce another header file and I think this is the right place to document "module-level" things, but just am suggesting caution when introducing _new_ module headers that may not be compatible with the code's expectations.

**Comment by gheber** [comment]
> > > Why create the H5module.h header?
> > 
> > 
> > Doxygen has the concept of modules, which, I think, is a good fit for HDF5 modules. There is API documentation (functions, structures, etc.), but perhaps also _module-level documentation_. It's also a convenient placeholder for grouping certain APIs within a given module, which is to a degree arbitrary. See for example `H5Fmodule.h`, where we separated MDC, SWMR, and parallel calls. Alternatively, we could have chosen Beginner, Intermediate, and Advanced, or something else. I think of it as a useful (documentation-)structuring aid, and it makes sense to have a place that's _consistent_ across HDF5 modules for that. Also, what if a module's public API involves multiple header files? The `H5` module came relatively late in the game after we had done most of the others and it just struck me as odd that it didn't have a `*module.h` file.
> > I think `H5Z` is a good example of module-level documentation. If you look at the stuff on [this page](https://portal.hdfgroup.org/display/HDF5/Filters) that might be clearer. I'll add it to this PR for reference. You can see it online [here](https://hdf5.io/develop/group___h5_z.html).
> 
> I _do_ like the idea, but the "module" files have a particular use in the code right now. For example, I'm not 100% certain that the macro definitions you have in the H5module.h file would be compatible with the H5 "module" code. (Those macros are used to configure various behavior for the module). I don't really want to introduce another header file and I think this is the right place to document "module-level" things, but just am suggesting caution when introducing _new_ module headers that may not be compatible with the code's expectations.

I just copied and pasted from other files. I can just remove the `#define`s. They have nothing to do with Doxygen. OK?

**Comment by qkoziol** [comment]
> > > > Why create the H5module.h header?
> > > 
> > > 
> > > Doxygen has the concept of modules, which, I think, is a good fit for HDF5 modules. There is API documentation (functions, structures, etc.), but perhaps also _module-level documentation_. It's also a convenient placeholder for grouping certain APIs within a given module, which is to a degree arbitrary. See for example `H5Fmodule.h`, where we separated MDC, SWMR, and parallel calls. Alternatively, we could have chosen Beginner, Intermediate, and Advanced, or something else. I think of it as a useful (documentation-)structuring aid, and it makes sense to have a place that's _consistent_ across HDF5 modules for that. Also, what if a module's public API involves multiple header files? The `H5` module came relatively late in the game after we had done most of the others and it just struck me as odd that it didn't have a `*module.h` file.
> > > I think `H5Z` is a good example of module-level documentation. If you look at the stuff on [this page](https://portal.hdfgroup.org/display/HDF5/Filters) that might be clearer. I'll add it to this PR for reference. You can see it online [here](https://hdf5.io/develop/group___h5_z.html).
> > 
> > 
> > I _do_ like the idea, but the "module" files have a particular use in the code right now. For example, I'm not 100% certain that the macro definitions you have in the H5module.h file would be compatible with the H5 "module" code. (Those macros are used to configure various behavior for the module). I don't really want to introduce another header file and I think this is the right place to document "module-level" things, but just am suggesting caution when introducing _new_ module headers that may not be compatible with the code's expectations.
> 
> I just copied and pasted from other files. I can just remove the `#define`s. They have nothing to do with Doxygen. OK?

That could work and might be the easiest solution.   I believe it would be better to have the macros though, with them working correctly.   Would you be open to collaborating on trying to get them working?  I could spend <=1hr in that direction today (just to time-box the effort) and see if it's possible to achieve in a reasonable amount of time.

**Comment by gheber** [comment]
> That could work and might be the easiest solution. I believe it would be better to have the macros though, with them working correctly. Would you be open to collaborating on trying to get them working? I could spend <=1hr in that direction today (just to time-box the effort) and see if it's possible to achieve in a reasonable amount of time.

Sure. I'm not sure though of how much help I can be. I'll just sit tight.

**Comment by qkoziol** [comment]
Great, I think that would be a good long-term investment.   I'll try cloning your PR and see if there's some low-cost changes that will make it fully compatible with the other module headers.

**Comment by qkoziol** [comment]
OK, I have an update to your changes that pulls the infrastructure source files into a more coherent "H5" module.   I'm running tests now, but how do I update the PR?

**Comment by qkoziol** [comment]
All the tests are passing for my changes.  @gheber - I've attached the patch to the comment, although I had to add a .txt suffix, to get github to upload it.

[git.diff.txt](https://github.com/HDFGroup/hdf5/files/5532789/git.diff.txt)

**Comment by gheber** [comment]
> All the tests are passing for my changes. @gheber - I've attached the patch to the comment, although I had to add a .txt suffix, to get github to upload it.
> 
> [git.diff.txt](https://github.com/HDFGroup/hdf5/files/5532789/git.diff.txt)

Thanks @qkoziol . I applied and committed the patch. Tests are running...

**Comment by gheber** [comment]
> > All the tests are passing for my changes. @gheber - I've attached the patch to the comment, although I had to add a .txt suffix, to get github to upload it.
> > [git.diff.txt](https://github.com/HDFGroup/hdf5/files/5532789/git.diff.txt)
> 
> Thanks @qkoziol . I applied and committed the patch. Tests are running...

Whoops. I missed a few...

**Review by qkoziol — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]
I didn't read all the text, but the structure looks fine.

**Review by lrknox — APPROVED** [review]

**Comment by gheber** [comment]
Thank you.

**Pull request merged**
