### PR TITLE
Bmr 1 10 hdffv 10480 hdffv 11159

### PR DESCRIPTION
**Pull request by bmribler**

### CODE REVIEW

**Review by byrnHDF — CHANGES_REQUESTED** [review]
I believe this was incorrect PR 1.10 to develop?

**Comment by derobins** [comment]
Should this be closed?

**Review by derobins — CHANGES_REQUESTED** [review]
This looks like it was incorrectly set up and should probably be closed.

**Comment by bmribler** [comment]
Yes, thanks!

**Pull request closed without merging**
