### PR TITLE
Add doxygen for high level modules.

### PR DESCRIPTION
**Pull request by vchoi-hdfgroup**

### CODE REVIEW

**Review by byrnHDF — APPROVED** [review]

**Comment by derobins** [comment]
Shouldn't this be merged into hdf5_1_10 and not 1.10/master?

**Comment by derobins** [comment]
Looks like the 1.12 HL docs went there, too. @vchoi-hdfgroup - you'll need to merge those to hdf5_1_12.

**Review by derobins — CHANGES_REQUESTED** [review]
This (and the 1.12 merge) need to go to hdf5_1_xx, not 1.x/master.

**Comment by vchoi-hdfgroup** [comment]
I will fix and merge the hl doxygen to hdf5_1_12 and hdf5_1_10.

**Pull request closed without merging**
