### PR TITLE
ci(Spack): add Ubuntu action

### PR DESCRIPTION
**Pull request by hyoklee**
Redo #2911 using my fork branch per @derobins request.
Address @brtnfld review.

### CODE REVIEW

**Review by derobins — CHANGES_REQUESTED** [review]
In the standup, we recommended modifying this to use the system resources instead of installing via spack, to get the time of this test down.

**Comment by hyoklee** [comment]
I won't change because it defeats the purpose of Spack testing (i.e., builds everything from source for HPC) if you use the system resource.
Time doesn't matter since Actions are faster than HDF5 PR merge frequency.

**Comment by brtnfld** [comment]
A couple of things. You should use the system's mpi compiler without having spack install it. The HPC facilities will always use the system's mpi and system compilers. So, as you are CI testing on Sunspot, Frontier, etc., make sure you are using the system compilers, not a spack-installed package. Secondly, we want to know if there are issues with system-supplied packages in our CI testing. We need to test these cases, in addition to, but run less frequently, the case where spack builds everything.

**Comment by hyoklee** [comment]
@brtnfld , it's irrelevant. I don't use this Action for HPC testing.

**Comment by brtnfld** [comment]
What use case are you testing, then? Most spack users try to use system resources when available.

**Comment by hyoklee** [comment]
This is a quick CI check if HDF5 develop branch accidentally breaks `spack install hdf5@develop` from Spack develop branch.

**Comment by derobins** [comment]
We're going to take a different strategy when it comes to Spack testing

**Pull request closed without merging**
