### PR TITLE
Update clang config

### PR DESCRIPTION
**Pull request by qkoziol**
Put H5E_BEGIN_TRY / H5E_END_TRY on separate lines, empty C++ methods on separate lines, understand that ALL_MEMBERS / UNIQUE_MEMBERS are foreach macros, and properly skip the 'config' directory in the find command without emiting a warning

### CODE REVIEW

**Comment by qkoziol** [comment]
The modifications to the .clang-format and bin/format_source* files are the important changes.

**Review by byrnHDF — APPROVED** [review]

**Comment by lrknox** [comment]
@qkoziol were all of the changes to files other than .clang-format and bin/format_source* files made by the formatter?  If so, merging to other branches should just merge the changes to those files, and the formatter will take care of the rest?

**Review by lrknox — APPROVED** [review]

**Comment by qkoziol** [comment]
> @qkoziol were all of the changes to files other than .clang-format and bin/format_source* files made by the formatter? If so, merging to other branches should just merge the changes to those files, and the formatter will take care of the rest?

Yep

**Review by derobins — APPROVED** [review]
Definitely an improvement

**Pull request merged**
