### PR TITLE
Change doxygen version from 1.10.0 to 1.9.7

### PR DESCRIPTION
**Pull request by byrnHDF**

### CODE REVIEW

**Comment by ajelenak** [comment]
Why this downgrade? I've been building the docs with doxygen 1.10 for a few weeks now.

**Comment by byrnHDF** [comment]
> Why this downgrade? I've been building the docs with doxygen 1.10 for a few weeks now.

Evidently. it has a problem with the NavTree - 1.10.0 doesn't display it 1.9.7 does. Proof was the generated docs in gh-pages.

**Comment by brtnfld** [comment]
Is it an issue with Doxygen itself or our docs? Did something change for 1.10.0 that we need to fix?

**Comment by byrnHDF** [comment]
> Is it an issue with Doxygen itself or our docs? Did something change for 1.10.0 that we need to fix?

I believe doxygen, but maybe there was a change that needs to be investigated to work with 1.10.0.

**Review by lrknox — APPROVED** [review]

**Comment by brtnfld** [comment]
I searched the GitHub issues and did not see any problems related to a missing navtree. I used the doxygen master, and I could not get the HDF5 develop or HDF5 1.14.x to show the navtree. Should we submit an issue with Doxgen?

FYI, unrelated:

/home/brtnfld/packages/hdf5.brtnfld/java/src/hdf/hdf5lib/H5.java:10063: warning: argument 'fapl_id' of command @param is not found in the argument list of H5::H5Pget_external(long plist, int idx, long name_size, String[] name, long[] size)
/home/brtnfld/packages/hdf5.brtnfld/java/src/hdf/hdf5lib/H5.java:10063: warning: argument 'fapl_id' of command @param is not found in the argument list of H5::H5Pget_external(long plist, int idx, long name_size, String[] name, long[] size)
/home/brtnfld/packages/hdf5.brtnfld/java/src/hdf/hdf5lib/H5.java:10063: warning: argument 'efc_size' of command @param is not found in the argument list of H5::H5Pget_external(long plist, int idx, long name_size, String[] name, long[] size)
/home/brtnfld/packages/hdf5.brtnfld/java/src/hdf/hdf5lib/H5.java:13922: warning: argument 'obj_id' of command @param is not found in the argument list of H5::H5Tenum_create(long base_id)

**Comment by ajelenak** [comment]
There is a custom .js file for our docs: hdf5_navtree_hacks.js. Probably good to first try without it before reporting to doxygen.

**Comment by byrnHDF** [comment]
I have found a number of issues with 1.10.0 and navtree problems - nothing with our exact problem. Note that we do have a custom css and a custom javascript file involved that could be causing the issue.

FYI here is an interesting possibility to use instead:  https://github.com/jothepro/doxygen-awesome-css

**Comment by ajelenak** [comment]
> FYI here is an interesting possibility to use instead: https://github.com/jothepro/doxygen-awesome-css

I've been testing it for two weeks now.

**Comment by byrnHDF** [comment]
> > FYI here is an interesting possibility to use instead: https://github.com/jothepro/doxygen-awesome-css
> 
> I've been testing it for two weeks now.

Then please put in a PR if it is a better replacement for our custom files!

**Review by jhendersonHDF — APPROVED** [review]

**Pull request merged**
