### PR TITLE
Add API support for Fortran MPI_F08 module definitions.

### PR DESCRIPTION
**Pull request by brtnfld**
Adds support for MPI's MPI_F08 module datatypes: type(MPI_COMM) and type(MPI_INFO) for HDF5 APIs:

H5PSET_FAPL_MPIO_F, H5PGET_FAPL_MPIO_F,  H5PSET_MPI_PARAMS_F, H5PGET_MPI_PARAMS_F

Includes tests and updated documentation.

See: #3951

### CODE REVIEW

**Review by epourmal — APPROVED** [review]
Looks good to me. Question: is there any way to avoid code duplication in mpi_para.F90 using ifdef? The only difference is the type definition for info and comm variables, rigth?

**Comment by brtnfld** [comment]
My assumption that TYPE(MPI*) is C interpretable is wrong, as it is for  MPICH but not OpenMPI; I need to instead go back to using  MPI_Comm_f2c, and I'll rework the test to simplify it.

ref. https://github.com/open-mpi/ompi/issues/12274

**Comment by epourmal** [comment]
> My assumption that TYPE(MPI*) is C interpretable is wrong, as it is for MPICH but not OpenMPI; I need to instead go back to using MPI_Comm_f2c, and I'll rework the test to simplify it.
> 
> ref. [open-mpi/ompi#12274](https://github.com/open-mpi/ompi/issues/12274)

I see. It would be really nice to get rid of the wrappers, but I guess, it will take time...

**Comment by brtnfld** [comment]
It's more straightforward to rewrite the test if I get into generic types (type(*)) or use classes; I'm not sure I want to introduce that complexity/Fortran standards into the tests.

**Review by byrnHDF — APPROVED** [review]

**Pull request merged**
