### PR TITLE
Fix typos found in the rest of the hdf5 code-base

### PR DESCRIPTION
**Pull request by luzpaz**
## Describe your changes

Fix follow-up typos to #1983

## Issue ticket number (GitHub or JIRA)

n/a

## Checklist before requesting a review
- [ ] My code conforms to the guidelines in CONTRIBUTING.md
- [ ] I made an entry in release_docs/RELEASE.txt (bug fixes, new features)
- [ ] I added a test (bug fixes, new features)

### CODE REVIEW

**Comment by luzpaz** [comment]
I've separated out [06b8403](https://github.com/HDFGroup/hdf5/pull/1985/commits/06b8403d99757c7d20f1eed530cf317c3d84de4b) for convenience. Please review if this is a possible bugfix.

**Comment by brtnfld** [comment]
How are these new spelling errors getting past codespell? Were there merges where codespell errors were ignored?

**Comment by luzpaz** [comment]
@brtnfld I'm x-refing different non-standard codespell dictionaries + using non-codespell approach as well.

**Comment by derobins** [comment]
@byrnHDF - Why aren't the clang-format changes being auto-applied?

**Review by byrnHDF — APPROVED** [review]

**Comment by derobins** [comment]
> I've separated out [06b8403](https://github.com/HDFGroup/hdf5/pull/1985/commits/06b8403d99757c7d20f1eed530cf317c3d84de4b) for convenience. Please review if this is a possible bugfix.

Yeah, that's a real bug. It's probably best to revert that in your PR and create a separate PR for it.

If you fix the clang format issue (not sure why that's not being automatically fixed by GitHub), we can get this merged in quickly.

**Comment by byrnHDF** [comment]
clang-format only commits on fork

**Comment by luzpaz** [comment]
Reverted bugfix commit + added clang-format fix.

**Review by lrknox — APPROVED** [review]

**Comment by lrknox** [comment]
I wondered the same thing, and checked the 3 misspellings in H5ACpkg.h.  they were there in the Dec7 commit, and there were no commits to that file since, so codespell apparently didn't notice them.

________________________________

**Review by derobins — APPROVED** [review]

**Pull request merged**
