### PR TITLE
msvc: don't declare `HAVE_TIMEZONE` for older MSVC

### PR DESCRIPTION
**Pull request by mathstuf**
It was introduced in MSVC 15 (Visual Studio 2017).

### CODE REVIEW

**Comment by mathstuf** [comment]
Ah…Intel OneAPI definitely needs considered here. Not sure what's up with the other failure off-hand.

**Comment by jhendersonHDF** [comment]
It looks like the vast majority of these failures are probably because of the #ifdef structure in https://github.com/HDFGroup/hdf5/blob/develop/src/H5system.c#L207 and because of `HAVE_TIMEZONE` not getting defined for some reason. Though, according to the CMake docs, `MSVC_VERSION` is preferred over `MSVC14`, so you might try something like:

```Cmake
if (MSVC_VERSION GREATER_EQUAL 1910)
```

based on https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html#variable:MSVC_VERSION

**Comment by mathstuf** [comment]
OneAPI probably needs some way to detect what backing runtime/headers are available too.

**Comment by byrnHDF** [comment]
> It looks like the vast majority of these failures are probably because of the #ifdef structure in https://github.com/HDFGroup/hdf5/blob/develop/src/H5system.c#L207 and because of `HAVE_TIMEZONE` not getting defined for some reason. Though, according to the CMake docs, `MSVC_VERSION` is preferred over `MSVC14`, so you might try something like:
> 
> ```cmake
> if (MSVC_VERSION GREATER_EQUAL 1910)
> ```
> 
> based on https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html#variable:MSVC_VERSION

This, MSVC_VERSION, is the preferred format .

**Review by byrnHDF — CHANGES_REQUESTED** [review]
Use MSVC_VERSION

**Review by derobins — APPROVED** [review]

**Review by byrnHDF — APPROVED** [review]

**Pull request merged**
