### PR TITLE
Check in generated files in src

### PR DESCRIPTION
**Pull request by derobins**
These files are infrequently updated and generating them adds an annoying dependency on Perl. We're checking them in and will probably add a GitHub action to check if anything is stale when creating a PR.

Adds:
    * H5Edefin.h
    * H5Einit.h
    * H5Emajdef.h
    * H5Emindef.h
    * H5Epubgen.h
    * H5Eterm.h
    * H5overflow.h
    * H5version.h

### CODE REVIEW

**Comment by derobins** [comment]
Adding these back in allows us to more easily test MinGW, which is a platform we care about.

**Comment by derobins** [comment]
I'll add a GitHub issue to check for freshness at a later date

**Review by mattjala — APPROVED** [review]

**Review by bmribler — APPROVED** [review]
Thank you!

**Review by qkoziol — APPROVED** [review]
Still have a dependency on Perl, ultimately...

**Pull request merged**
