### PR TITLE
Rework of PR #826

### PR DESCRIPTION
**Pull request by brtnfld**
Made changes suggested in review:

H5fget_name_f len_trim fix #826

### CODE REVIEW

**Comment by brtnfld** [comment]
@jhaiduce, let me know if I missed something. Thanks.

**Comment by jhaiduce** [comment]
> @jhaiduce, let me know if I missed something. Thanks.

Looks good to me. It looks like the biggest difference from PR #826 is the change from using a dataset to a group in get_name_test. But that distinction probably doesn't matter for the problem identified in issue #825.

Not sure if this matters to anyone, but there is trailing whitespace on Line 24 of fortran/test/tH5F.F90.

**Comment by byrnHDF** [comment]
Does this need a Release.txt entry?

**Comment by byrnHDF** [comment]
Can this change be applied to 1.12, 1.10, or 1.8?

**Comment by lrknox** [comment]
Configurations with xlf and -qintsize=8 fail the same test in 1.12, 1.10 and 1.8;  change is needed for all branches.

**Review by epourmal — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

**Comment by brtnfld** [comment]
> Can this change be applied to 1.12, 1.10, or 1.8?

Yes.

**Pull request merged**
