### PR TITLE
H5Spoint.c:  Fix mistake in comment

### PR DESCRIPTION
**Pull request by Dave-Allured**

### CODE REVIEW

**Review by derobins — APPROVED** [review]
Thanks!

**Review by byrnHDF — APPROVED** [review]

**Comment by Dave-Allured** [comment]
Shall I back port this to 1.12 and 1.14 maintenance branches?  Is there a bulk procedure, or do I make individual PR's?  (Indeed a minor issue, but confused me while I was researching format control.)

**Comment by jhendersonHDF** [comment]
Hi @Dave-Allured, it'd be appreciated if you could back port this to any of the branches among the `hdf5_1_10`, `hdf5_1_12` and `hdf5_1_14` branches where it applies. Typically we just create an individual PR for each branch and I usually edit the title of the PR to start with, e.g. "[1.14 Merge]" to distinguish it, but that's just the easiest way for me to see the difference.

**Comment by Dave-Allured** [comment]
> ... back port this to any of the branches among the `hdf5_1_10`, `hdf5_1_12` and `hdf5_1_14` branches where it applies.

Done for 1.12 and 1.14.  Please remove the merge 1.10 tag, it does not apply.  Thanks.

**Comment by jhendersonHDF** [comment]
Thanks for the PRs!

**Pull request merged**
