### PR TITLE
Add Doxygen for H5S_ALL, _PLIST, and _BLOCK

### LINKED ISSUE #688: Add doxygen info for H5S_ALL, H5S_BLOCK, and H5S_PLIST
per subject

### PR DESCRIPTION
**Pull request by derobins**
Fixes #688

### CODE REVIEW

**Comment by derobins** [comment]
Screenshot 2023-05-05 at 6 26 57 PM
Screenshot 2023-05-05 at 6 27 05 PM

**Comment by derobins** [comment]
Note that I slightly altered the text after I took the screenshots.

**Comment by derobins** [comment]
Needs care in moving downstream!

**Review by byrnHDF — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]

**Comment by derobins** [comment]
Fixes #688

**Pull request merged**
