### PR TITLE
update stat arg for apple

### PR DESCRIPTION
**Pull request by brtnfld**
Changed the "stat" arg depending on OS type.
Added parallel Fortran async test to CMake
Removed duplicate H5_ih_info_t declaration in Fortran source.

Checked parallel on Mac 14.0  with mpich 4.1.2 for both Autotools and Cmake.

### CODE REVIEW

**Comment by derobins** [comment]
For anyone who doesn't have easy access to both operating systems...

Linux:

       -c  --format=FORMAT
              use the specified FORMAT instead of the default; output a newline after each use of FORMAT

**Comment by derobins** [comment]
MacOS:

     -f format
             Display information using the specified format.  See the Formats section for a description of valid
             formats.
             
     -s      Display information in “shell output” format, suitable for initializing variables.

**Review by byrnHDF — APPROVED** [review]

**Comment by jhendersonHDF** [comment]
> MacOS:
> 
> ```
>  -f format
>          Display information using the specified format.  See the Formats section for a description of valid
>          formats.
>          
>  -s      Display information in “shell output” format, suitable for initializing variables.
> ```

Does specifying %i after -f still give you the file inode value on macOS? That's what we're after

**Comment by brtnfld** [comment]
datum   A required field specifier, being one of the following:


             i       file's inode number (st_ino).

It seems to work correctly from the command line.

**Comment by brtnfld** [comment]
PR is in draft because I've not tried it on Apple yet, and I want to check for any other gotchas. Installing mpich is giving me issues because of the -commons issue with Xcode 15

**Review by hyoklee — APPROVED** [review]
Proof: https://github.com/hyoklee/hdf5/actions/runs/6591892808/job/17911451281

**Review by lrknox — APPROVED** [review]

**Pull request merged**
