### PR TITLE
Add check for PERL_FOUND around actual test

### PR DESCRIPTION
**Pull request by byrnHDF**
Fixes Skip H5SHELL-test_flush_refresh Test for CMake #4394

### CODE REVIEW

**Review by derobins — APPROVED** [review]

**Comment by derobins** [comment]
I wish there were a portable way of doing this without the Perl dependency

**Comment by derobins** [comment]
You don't need Perl for this test, though. The test will run fine if the system's date command takes %s (true on Linux and Mac, but not some oddballs like Solaris).

Also, this doesn't have a Powershell equivalent and doesn't get tested on Windows. We should add GitHub issues for anything that is tested under Linux but not Windows due to no Powershell equivalent.

**Comment by byrnHDF** [comment]
However  -the .sh file is not created earlier so cannot execute the test.
We would need to allow the configure file to happen.

**Review by lrknox — APPROVED** [review]

**Comment by hyoklee** [comment]
Test passed: https://github.com/hyoklee/actions/actions/runs/11926479719

**Pull request merged**
