### PR TITLE
Rename INSTALL_Auto.txt to INSTALL_Autotools.txt

### PR DESCRIPTION
**Pull request by derobins**

### CODE REVIEW

**Comment by derobins** [comment]
Weird that the link checker isn't smart enough to handle updated links in the PR

**Review by byrnHDF — APPROVED** [review]

**Review by brtnfld — COMMENTED** [review]
I think we should transition to using markdown for text docs, as many people now read this information from GitHub.

**Comment by derobins** [comment]
> I think we should transition to using markdown for text docs, as many people now read this information from GitHub.

Agree, but that's a task for a different PR

**Comment by brtnfld** [comment]
Why is this PR necessary if a future change to the markdown file will require renaming again?

**Comment by derobins** [comment]
> Why is this PR necessary if a future change to the markdown file will require renaming again?

The odds of getting INSTALL_Auto.md seem high and I wasn't thinking about converting this to markdown when I created the PR. The name was just less than optimal.

**Review by brtnfld — APPROVED** [review]

**Pull request merged**
