### PR TITLE
ci: add h5py action (#2986)

### LINKED ISSUE #2986: [Feature Request] Add h5py test action.
Revisit #501.

### PR DESCRIPTION
**Pull request by hyoklee**
Close #2986.

### CODE REVIEW

**Comment by brtnfld** [comment]
I would only test external packages daily, not for every PR.

**Comment by derobins** [comment]
> I would only test external packages daily, not for every PR.

Agree. This should run overnight.

**Comment by derobins** [comment]
I'm excited about testing h5py, but we should check out h5py directly and not use spack. This should not take two hours. On BuildBot it takes ~5-10 min.

**Comment by hyoklee** [comment]
@derobins and @brtnfld , I made it as a cron job.

**Review by derobins — APPROVED** [review]

**Review by mattjala — APPROVED** [review]

**Pull request merged**
