### PR TITLE
Removes cmake_ext_mod (files moved to cmake)

### PR DESCRIPTION
**Pull request by derobins**
At one time this content was a git submodule shared between several
projects but that time has long passed.

### CODE REVIEW

**Comment by derobins** [comment]
This change is @byrnHDF approved, btw.

**Comment by derobins** [comment]
For anyone reviewing:

- cmake_ext_mod files moved to cmake
- Only two files had to be combined: CtestCustom.cmake and ConfigureChecks.cmake
- All other file changes involved path renames

**Review by byrnHDF — APPROVED** [review]
We should consider removing the FindSZIP.cmake file as it is out of date and does not even consider the aec szip replacement library.
The other choice is to fix it.

**Review by lrknox — APPROVED** [review]

**Comment by derobins** [comment]
> We should consider removing the FindSZIP.cmake file as it is out of date and does not even consider the aec szip replacement library. The other choice is to fix it.

I'll create an issue for that

**Pull request merged**
