### PR TITLE
Remove CMake-3.31.0 warnings

### PR DESCRIPTION
**Pull request by hyoklee**
This PR will remove warnings like below:

```
CMake Warning (dev) at fortran/src/CMakeLists.txt:132 (add_custom_command):
  The following keywords are not supported when using
  add_custom_command(TARGET): DEPENDS.
```

Ref: https://github.com/lukka/get-cmake/releases/tag/v3.31.0

### CODE REVIEW

**Review by byrnHDF — APPROVED** [review]
Seems okay as this is using the TARGET form of add_custom_command.
Wonder why we didn't use the other form, OUTPUT?

**Review by lrknox — APPROVED** [review]

**Comment by brtnfld** [comment]
Can you explain this further so I understand? The DEPENDS option specifies the files on which the command depends. Are you saying this DEPENDS is redundant because TARGET already handles the interdependency between build files?

Is one of the Github actions to check this with the minimum version of CMake to ensure it still works for the older versions?

**Comment by byrnHDF** [comment]
> Can you explain this further so I understand? The DEPENDS option specifies the files on which the command depends. Are you saying this DEPENDS is redundant because TARGET already handles the interdependency between build files?

There are two forms of the add_custom_command. 
add_custom_command(OUTPUT ...)  and add_custom_command(TARGET ...)
The OUTPUT command supports DEPENDS the TARGET version does not and never did since at least 3.18.

**Comment by brtnfld** [comment]
Right, so how is CMake getting informed of the dependency if it ignored the DEPENDCY command?

**Comment by byrnHDF** [comment]
Most likely from the actual target properties.

**Review by brtnfld — APPROVED** [review]

**Pull request merged**
