### PR TITLE
Bump Autoconf version to 2.71

### PR DESCRIPTION
**Pull request by derobins**
Required for building with Intel's oneAPI

### CODE REVIEW

**Review by byrnHDF — APPROVED** [review]

**Comment by derobins** [comment]
I feel like we are at the point where we *have* to merge this in. If we don't, we risk breaking oneAPI unless we are SUPER careful (and I'm not a fan of fragile manual steps).

If anyone has any other ideas about how we can manage the tension between "need to build HDF5 on older machines" and "need to support oneAPI", I'm all ears.

**Review by jhendersonHDF — APPROVED** [review]

**Comment by jhendersonHDF** [comment]
> I feel like we are at the point where we _have_ to merge this in. If we don't, we risk breaking oneAPI unless we are SUPER careful (and I'm not a fan of fragile manual steps).
> 
> If anyone has any other ideas about how we can manage the tension between "need to build HDF5 on older machines" and "need to support oneAPI", I'm all ears.

Considering that Slackware moved to 2.71 back in Feb. of last year, I think it's a safe bet at this point that most others will have moved along too.

**Review by brtnfld — APPROVED** [review]
Plus, if a user really wants to regenerate using 2.69, it is a one-line change since there are no 2.71 nuances.

Although, a search on GitHub reported ~12k using 2.69 compared to 760 using 2.71

**Review by qkoziol — APPROVED** [review]

**Comment by hyoklee** [comment]
Where is oneAPI Action to test?

**Comment by derobins** [comment]
> Where is oneAPI Action to test?

That's going to take some time to set up, but it's on the agenda. One thing at a time.

**Comment by hyoklee** [comment]
configure fails with `--enable-parallel`.

**Pull request merged**
