### PR TITLE
Fix improper include of build directory (#2422, #2621)

### LINKED ISSUE #2422: [BUG] Packaging HDF5 1.14 references build directory in settings
**Describe the bug**
After https://github.com/HDFGroup/hdf5/commit/27bb358f7ab1d23f3f8ce081c6b4f1602033e4d7#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810 the hdf5 settings file references the directory hdf5 was build in.

**Expected behavior**
Includes should not reference a temporary build directory.

**Platform (please complete the following information)**
 - HDF5 version: 1.14.0
 - OS and version: macOS 13.2
 - Compiler and version: CLang
 - Build system: latest version of all tools to use with configure
 - Any configure options you specified: https://github.com/Homebrew/homebrew-core/pull/119504/files#diff-932622d999a2cb8276fb857b7d97c7d3a2c3a6694db7c01f641f00ecd71d18c2R50-R59
 - MPI library and version: 1.14.0

**Additional context**
This was discovered at https://github.com/Homebrew/homebrew-core/pull/119504

### LINKED ISSUE #2621: [BUG] HDF5 C++ 1.14.0 includes H5FDsubfiling build path
**Describe the bug**
Using HDF5 C++ library with cmake results in error:

```
CMake Error in CMakeLists.txt:
  Imported target "hdf5::hdf5_cpp" includes non-existent path

    "/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

The path is from HDF5 build directory which is deleted after install

**Expected behavior**
No build path should be included anywhere, because H5FDsubfiling headers are already installed in the system.

**Platform (please complete the following information)**
 - HDF5 version 1.14.0
 - OS and version: Linux Debian 11
 - Compiler and version: GCC 12.2.0
 - Build system (e.g. CMake, Autotools) and version: Autotools
 - Any configure options you specified
 `./configure --prefix=/usr/local --enable-cxx`

**Additional context**
Path to H5FDsubfiling is included in 3 places:

```
/usr/local/bin/h5c++:H5BLD_CPPFLAGS=" -I/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling "
/usr/local/bin/h5cc:H5BLD_CPPFLAGS=" -I/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling "
/usr/local/lib/libhdf5.settings:                    AM_CPPFLAGS:  -I/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling
```

Removing flags from h5c++ and h5cc fixes the problem.

### PR DESCRIPTION
**Pull request by jhendersonHDF**

### CODE REVIEW

**Review by brtnfld — APPROVED** [review]
LGTM

**Review by byrnHDF — APPROVED** [review]

**Comment by brtnfld** [comment]
Unrelated: But does something like the below allow a clickable hyperlink in the Release.txt (assuming Release.md instead of Release.txt)?

```
([#2422][i2422])
[i2422]: https://github.com/HDFGroup/hdf5/issues/2422

```

**Comment by jhendersonHDF** [comment]
> 

I just tried it. See the README from GitHub at https://github.com/jhendersonHDF/hdf5/tree/feature/api_tests/test/API

**Comment by brtnfld** [comment]
Nice, that's handy. I'll ask Larry if we can change to .md instead.

**Pull request merged**
