### PR TITLE
docs: in -> out (#2514)

### PR DESCRIPTION
**Pull request by hyoklee**

### CODE REVIEW

**Review by jhendersonHDF — APPROVED** [review]

**Review by byrnHDF — APPROVED** [review]

**Comment by byrnHDF** [comment]
Do these changes need to happen in 1.14, 1.12, 1.10? Then add the merge to labels.

**Comment by hyoklee** [comment]
@byrnHDF I can't add labels. I don't have permission.

**Comment by hyoklee** [comment]
@byrnHDF , does adding labels automatically fix 1.10 as well?

**Comment by byrnHDF** [comment]
> @byrnHDF , does adding labels automatically fix 1.10 as well?

No, those PRs must be created, these labels indicate that those branches should get this change too.

**Comment by hyoklee** [comment]
https://github.com/marketplace/actions/label-actions

**Comment by byrnHDF** [comment]
Due to code and feature differences between branches, automatically creating a PR for another branch is not advisable.

**Review by lrknox — APPROVED** [review]

**Comment by lrknox** [comment]
> @byrnHDF I can't add labels. I don't have permission.

Not Merge - to 1.12?

**Pull request merged**
