### PR TITLE
Transferred RM blocks to develop

### PR DESCRIPTION
**Pull request by bmribler**
H5D and H5G in this PR.  I still have H5R which doesn't have RM blocks yet.

### CODE REVIEW

**Comment by qkoziol** [comment]
HTML is OK in Doxygen comments?

**Review by qkoziol — APPROVED** [review]

**Review by vchoi-hdfgroup — COMMENTED** [review]
Are the files synced up with hdfgroup develop yet?

**Review by gheber — COMMENTED** [review]
Please modify `H5Dmodule.h` and `H5Gmodule.h` before the closing `#endif /* ... */` as follows:
```
/**
 * \defgroup H5D H5D
 * \brief Dataset Interface
 * \todo Describe concisely what the functions in this module are about.
 */
```
and
```
/**
 * \defgroup H5G H5G
 * \brief Group Interface
 * \todo Describe concisely what the functions in this module are about.
 */
```

See `H5Fmodule.h` as an example.

**Comment by gheber** [comment]
This causes the following Doxygen errors:
```
Generating index page...
/home/gerdheber/GitHub/hdf5/doxygen/dox/mainpage.dox:7: warning: unable to resolve reference to `H5D' for \ref command
/home/gerdheber/GitHub/hdf5/doxygen/dox/mainpage.dox:7: warning: unable to resolve reference to `H5D' for \ref command
...
/home/gerdheber/GitHub/hdf5/doxygen/dox/mainpage.dox:13: warning: unable to resolve reference to `H5G' for \ref command
/home/gerdheber/GitHub/hdf5/doxygen/dox/mainpage.dox:13: warning: unable to resolve reference to `H5G' for \ref command
...
```

**Comment by gheber** [comment]
I see this Doxygen error, which comes from `H5Gpublic.h`:
```
Generating docs for file /home/gerdheber/GitHub/hdf5/src/H5Gpublic.h...
/home/gerdheber/GitHub/hdf5/src/H5Gpublic.h:239: warning: block marked with [H5G_info_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Gpublic.h, found it 0 times

/home/gerdheber/GitHub/hdf5/src/H5Gpublic.h:273: warning: block marked with [H5G_info_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Gpublic.h, found it 0 times
```
The reason is that the `H5G_info_t` definition needs to be surrounded by `//! [H5G_info_t_snip]` comments, i.e.,
```
//! [H5G_info_t_snip]
typedef struct H5G_info_t {
...
} H5G_info_t;
//! [H5G_info_t_snip]
```

**Comment by gheber** [comment]
There are also several errors in `H5D`. Please address them or ask for help.
```
Generating docs for file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h...
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:200: warning: argument 'loc_id' of command @param is not found in the argument list of H5Dcreate_anon(hid_t file_id, hid_t type_id, hid_t space_id, hid_t plist_id, hid_t dapl_id)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:200: warning: argument 'dcpl_id' of command @param is not found in the argument list of H5Dcreate_anon(hid_t file_id, hid_t type_id, hid_t space_id, hid_t plist_id, hid_t dapl_id)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:258: warning: The following parameters of H5Dcreate_anon(hid_t file_id, hid_t type_id, hid_t space_id, hid_t plist_id, hid_t dapl_id) are not documented:
  parameter 'file_id'
  parameter 'plist_id'
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1059: warning: argument 'fill_type_id' of command @param is not found in the argument list of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1059: warning: argument 'buf_type_id' of command @param is not found in the argument list of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1059: warning: argument 'space_id' of command @param is not found in the argument list of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1099: warning: The following parameters of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space) are not documented:
  parameter 'fill_type'
  parameter 'buf_type'
  parameter 'space'
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1331: warning: block marked with [H5D_gather_func_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h, found it 0 times

/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:555: warning: argument 'offset' of command @param is not found in the argument list of H5Dget_chunk_info(hid_t dset_id, hid_t fspace_id, hsize_t chk_idx, hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:600: warning: The following parameters of H5Dget_chunk_info(hid_t dset_id, hid_t fspace_id, hsize_t chk_idx, hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size) are not documented:
  parameter 'coord'
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:524: warning: argument 'offset' of command @param is not found in the argument list of H5Dget_chunk_info_by_coord(hid_t dset_id, const hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:552: warning: The following parameters of H5Dget_chunk_info_by_coord(hid_t dset_id, const hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size) are not documented:
  parameter 'coord'
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:981: warning: block marked with [H5D_operator_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h, found it 0 times

/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:261: warning: argument 'loc_id' of command @param is not found in the argument list of H5Dopen2(hid_t file_id, const char *name, hid_t dapl_id)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:292: warning: The following parameters of H5Dopen2(hid_t file_id, const char *name, hid_t dapl_id) are not documented:
  parameter 'file_id'
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:624: warning: argument 'dxpl_id' of command @param is not found in the argument list of H5Dread(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, void *buf)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:717: warning: The following parameters of H5Dread(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, void *buf) are not documented:
  parameter 'plist_id'
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1247: warning: block marked with [H5D_scatter_func_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h, found it 0 times

/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1032: warning: argument 'dset_id' of command @param is not found in the argument list of H5Dvlen_get_buf_size(hid_t dataset_id, hid_t type_id, hid_t space_id, hsize_t *size)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1056: warning: The following parameters of H5Dvlen_get_buf_size(hid_t dataset_id, hid_t type_id, hid_t space_id, hsize_t *size) are not documented:
  parameter 'dataset_id'
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:721: warning: argument 'dxpl_id' of command @param is not found in the argument list of H5Dwrite(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, const void *buf)
/home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:828: warning: The following parameters of H5Dwrite(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, const void *buf) are not documented:
  parameter 'plist_id'
```

**Comment by bmribler** [comment]
> Are the files synced up with hdfgroup develop yet?

They should be.

**Comment by bmribler** [comment]
> HTML is OK in Doxygen comments?

I should be.  We've been doing it but I think we want to keep that to the minimum.  Gerd?

**Comment by bmribler** [comment]
Gerd, I'll fix all the issues you found.  Thanks!

**Comment by bmribler** [comment]
Redo due to too much conflicts.  Requested changes here will be applied to the new PR.

**Comment by bmribler** [comment]
> There are also several errors in `H5D`. Please address them or ask for help.
> 
> ```
> Generating docs for file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h...
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:200: warning: argument 'loc_id' of command @param is not found in the argument list of H5Dcreate_anon(hid_t file_id, hid_t type_id, hid_t space_id, hid_t plist_id, hid_t dapl_id)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:200: warning: argument 'dcpl_id' of command @param is not found in the argument list of H5Dcreate_anon(hid_t file_id, hid_t type_id, hid_t space_id, hid_t plist_id, hid_t dapl_id)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:258: warning: The following parameters of H5Dcreate_anon(hid_t file_id, hid_t type_id, hid_t space_id, hid_t plist_id, hid_t dapl_id) are not documented:
>   parameter 'file_id'
>   parameter 'plist_id'
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1059: warning: argument 'fill_type_id' of command @param is not found in the argument list of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1059: warning: argument 'buf_type_id' of command @param is not found in the argument list of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1059: warning: argument 'space_id' of command @param is not found in the argument list of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1099: warning: The following parameters of H5Dfill(const void *fill, hid_t fill_type, void *buf, hid_t buf_type, hid_t space) are not documented:
>   parameter 'fill_type'
>   parameter 'buf_type'
>   parameter 'space'
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1331: warning: block marked with [H5D_gather_func_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h, found it 0 times
> 
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:555: warning: argument 'offset' of command @param is not found in the argument list of H5Dget_chunk_info(hid_t dset_id, hid_t fspace_id, hsize_t chk_idx, hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:600: warning: The following parameters of H5Dget_chunk_info(hid_t dset_id, hid_t fspace_id, hsize_t chk_idx, hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size) are not documented:
>   parameter 'coord'
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:524: warning: argument 'offset' of command @param is not found in the argument list of H5Dget_chunk_info_by_coord(hid_t dset_id, const hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:552: warning: The following parameters of H5Dget_chunk_info_by_coord(hid_t dset_id, const hsize_t *coord, unsigned *filter_mask, haddr_t *addr, hsize_t *size) are not documented:
>   parameter 'coord'
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:981: warning: block marked with [H5D_operator_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h, found it 0 times
> 
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:261: warning: argument 'loc_id' of command @param is not found in the argument list of H5Dopen2(hid_t file_id, const char *name, hid_t dapl_id)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:292: warning: The following parameters of H5Dopen2(hid_t file_id, const char *name, hid_t dapl_id) are not documented:
>   parameter 'file_id'
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:624: warning: argument 'dxpl_id' of command @param is not found in the argument list of H5Dread(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, void *buf)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:717: warning: The following parameters of H5Dread(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, void *buf) are not documented:
>   parameter 'plist_id'
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1247: warning: block marked with [H5D_scatter_func_t_snip] for \snippet should appear twice in file /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h, found it 0 times
> 
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1032: warning: argument 'dset_id' of command @param is not found in the argument list of H5Dvlen_get_buf_size(hid_t dataset_id, hid_t type_id, hid_t space_id, hsize_t *size)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:1056: warning: The following parameters of H5Dvlen_get_buf_size(hid_t dataset_id, hid_t type_id, hid_t space_id, hsize_t *size) are not documented:
>   parameter 'dataset_id'
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:721: warning: argument 'dxpl_id' of command @param is not found in the argument list of H5Dwrite(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, const void *buf)
> /home/gerdheber/GitHub/hdf5/src/H5Dpublic.h:828: warning: The following parameters of H5Dwrite(hid_t dset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t plist_id, const void *buf) are not documented:
>   parameter 'plist_id'
> ```

Gerd, I'm sorry that I didn't mention that this was just an initial draft to test out the procedure.  Initial feedbacks would be a bonus.  I will fix all warnings before the final version.

**Pull request closed without merging**
