### PR TITLE
Added more C++11 override keywords

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
Seems I didn't get them all last time... I used a newer clang here and I think this is all of them finally.

**Review by byrnHDF — APPROVED** [review]

**Comment by seanm** [comment]
@bmribler @qkoziol @derobins care to review?

**Comment by qkoziol** [comment]
Unfortunately, my confidence about these changes would be low.   More in @bmribler 's wheelhouse than mine. :-)

**Comment by seanm** [comment]
@bmribler if you're too busy, maybe you know of another C++ reviewer?

**Comment by seanm** [comment]
@gnuoyd @derobins know anyone that could review this?

**Review by bmribler — APPROVED** [review]
Sorry, I didn't see the messages...  I'm not sure about the format failure though.

**Comment by seanm** [comment]
Great, thanks!  Can these get into the 1.10.x branch too please?

**Comment by lrknox** [comment]
Yes, after a couple of days testing develop I’ll create pull requests to merge all recent pull requests that have been merged to develop but not to 1.12 and 1.10.

**Comment by seanm** [comment]
@lrknox I tracked down the remaining override warnings in [ITK](https://open.cdash.org/viewBuildError.php?type=1&buildid=7674769) to 4573b444eadc5267afd743db9c7f2aba9903bbb1 not being in `hdf5_1_12` (the development branch for future 1.12.x releases).

Could you backport it please?

**Comment by byrnHDF** [comment]
Will that require a higher C++ standard then what is already in 1.12. I know we changed the develop setting - not sure we can move 1.12 setting?

**Comment by seanm** [comment]
No, because `H5_OVERRIDE` is defined to nothing for old C++.

**Pull request merged**
