### PR TITLE
build(configure.ac): skip h5fuse.sh if subfiling VFD is not used (#3089)

### LINKED ISSUE #3089: Don't create `utils/subfiling_vfd/h5fuse.sh` if `--enable-subfiling-vfd` is not used.
**Describe the bug**

I see this message although I did not enable `subfiling_vfd`.

`config.status: creating utils/subfiling_vfd/h5fuse.sh`

**Expected behavior**

  I should not see the above message.

**Platform (please complete the following information)**
 - HDF5 version: Develop
 - OS and version: Ubuntu 22.04
 - Compiler and version: n/a
 - Build system: Autotools

### PR DESCRIPTION
**Pull request by hyoklee**
Close #3089.

### CODE REVIEW

**Review by derobins — CHANGES_REQUESTED** [review]
h5fuse isn't special. If we do one of these, we should do them all.

**Review by fortnern — APPROVED** [review]

**Comment by hyoklee** [comment]
> h5fuse isn't special. If we do one of these, we should do them all.

Please create another issue. Let's merge this one first and finish the rest one by one.

**Comment by jhendersonHDF** [comment]
Since the h5fuse script doesn't need the Subfiling VFD to be built and since I can definitely see use cases where a user would want to work with Subfiling VFD subfiles without having the Subfiling VFD available, I don't think we should make generating of the script dependent on whether the Subfiling VFD is built.

**Comment by derobins** [comment]
This is a useful tool even without the subfiling VFD so we'll leave it in

**Pull request closed without merging**
