### PR TITLE
H5S: fix const correctness for `space` parameters

### PR DESCRIPTION
**Pull request by mathstuf**
---
Split from #1640.

### CODE REVIEW

**Comment by jhendersonHDF** [comment]
Hey @mathstuf,

looks like we were tackling the same issue as each other! I ended up fixing this by removing const rather than adding it some places since it seems the selection iterator code may currently need to operate on the space during iteration and so the const seems a bit misleading.

**Comment by mathstuf** [comment]
Really? Where is the `const` being stripped away then as I think it was the iterator code that led me to adding `const` everywhere.

**Comment by jhendersonHDF** [comment]
> Really? Where is the `const` being stripped away then as I think it was the iterator code that led me to adding `const` everywhere.

Here's one such place in a previous PR: https://github.com/HDFGroup/hdf5/pull/1684/files#diff-ca61bfabd09b881fe4c59df5be0650fe189ebe672bb355e69392662c686e31a6.

Following a similar example in that file, I had marked the `dst_space` and `src_space` parameters as const, but then casted const away since the selection iterator code currently accepts a non-const `space` parameter. IMO, the selection iterator code should probably continue to accept a non-const `space` pointer for now, so I just removed const from the parameters to `H5D_select_io_mem`. It would likely be a good idea to have const and non-const versions of selection iterators in the future, but for now it seems best to leave this open.

In any case, if you build the latest HDF5 develop branch you should find all the H5S warnings addressed, unless I happened to miss one.

**Comment by derobins** [comment]
This has already been addressed in a different way.

**Pull request closed without merging**
