### PR TITLE
Turn off GitHub concurrent actions

### PR DESCRIPTION
**Pull request by derobins**
This cancels way too much stuff inappropriately. We need to better understand how this feature works.

### CODE REVIEW

**Comment by brtnfld** [comment]
Can you be more specific about what the issue is? Which PR actions failed due to their actions being canceled.

**Comment by derobins** [comment]
It might just have been the HDF-EOS5 actions that Jordan fixed, but I had multiple PRs over the weekend that would get cancelled and required constant restarts. It was driving me bananas.

**Review by bmribler — APPROVED** [review]

**Comment by jhendersonHDF** [comment]
I think as a workaround for the issue of cancelling older workflows for merge commits so that we only run workflows for the latest develop commit, we should change the CI so it doesn't run `on: push` and instead setup the workflow to run maybe once daily using https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by byrnHDF** [comment]
I am working on a workflow that does exactly that - still under dev but progressing.  Maybe we need to separate push (to fork) from pull-request and run different things depending on the situation.  
Once I get the daily workflow working we will have a chance to implement true multi-level CI from fork to DailyTesting.

**Pull request closed without merging**
