### PR TITLE
Lustre Bug on Perlmutter was fixed, subfiling no longer causes an issue.

### PR DESCRIPTION
**Pull request by brtnfld**
This is no longer an issue.

### CODE REVIEW

**Review by jhendersonHDF — APPROVED** [review]

**Comment by hyoklee** [comment]
@brtnfld , was it fixed for [NVIDA compiler](https://docs.nersc.gov/systems/perlmutter/software/) as well?

**Review by hyoklee — COMMENTED** [review]
Check NVIDIA as well.

**Comment by brtnfld** [comment]
It was a lustre bug, with nothing to do with the compiler.

**Comment by hyoklee** [comment]
Please revise the issue title. It's misleading. If it is Perlmutter Lustre specific issue, why is it here?

**Review by hyoklee — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

**Pull request merged**
