### PR TITLE
Fixes a wayward parenthesis in H5TS.c

### PR DESCRIPTION
**Pull request by derobins**

### CODE REVIEW

**Comment by derobins** [comment]
H5TS.c gets dirtied every time I run autogen.sh. It's driving me NUTS.

**Comment by qkoziol** [comment]
The code formatter will just put it back the other way... ;-)

**Comment by derobins** [comment]
> The code formatter will just put it back the other way... ;-)

Then the formatter is wrong and should change. It's completely ridiculous to have autogen dirty the repo. This has happened often enough to where I'm ready to cobble a script together that makes sure autogen.sh + git diff is clean before allowing a commit.

**Comment by derobins** [comment]
> The code formatter will just put it back the other way... ;-)

Also, nobody appears to be running the formatter. I just ran it over develop and 150 files changed. (This may be due to my version of LLVM, but version-specific formatting is _another_ problem that we could have)

**Review by lrknox — APPROVED** [review]

**Review by byrnHDF — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]

**Pull request merged**
